
typedef enum _ISO_8859_1_t
{
    WHITESPACE = 0x20,  //  
    EXCLAMATION_MARK,   // !
    QUOTATION_MARK,     // "
    NUMBER_SIGN,        // #
    DOLLAR_SIGN,        // $
    PERCENT_SIGN,       // %
    AMPERSAND,          // &
    APOSTROPHE,         // '
    BRACKET_OPEN,       // (
    BRACKET_CLOSE,      // )
    ASTERISK,           // *
    PLUS_SIGN,
    COMMA,
    MINUS_SIGN,
    PERIOD,
    SLASH,
    ZERO,
    ONE,
    TWO,
    THERE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    COLON,
    SEMICOLON,
    LESS_THAN_SIGN,
    EQUAL_SIGN,
    GREATER_THAN_SIGN,
    QUESTION_MARK,
    AT_SIGN,
    UPPER_A,
    UPPER_B,
    UPPER_C,
    UPPER_D,
    UPPER_E,
    UPPER_F,
    UPPER_G,
    UPPER_H,
    UPPER_I,
    UPPER_J,
    UPPER_K,
    UPPER_L,
    UPPER_M,
    UPPER_N,
    UPPER_O,
    UPPER_P,
    UPPER_Q,
    UPPER_R,
    UPPER_S,
    UPPER_T,
    UPPER_U,
    UPPER_V,
    UPPER_W,
    UPPER_X,
    UPPER_Y,
    UPPER_Z,
    SQUARE_BRACKET_OPEN,
    BACKSLASH,
    SQUARE_BRACKET_CLOSE,
    CARET,
    UNDERSCORE,
    GRAVE_ACCENT,
    LOWER_A,
    LOWER_B,
    LOWER_C,
    LOWER_D,
    LOWER_E,
    LOWER_F,
    LOWER_G,
    LOWER_H,
    LOWER_I,
    LOWER_J,
    LOWER_K,
    LOWER_L,
    LOWER_M,
    LOWER_N,
    LOWER_O,
    LOWER_P,
    LOWER_Q,
    LOWER_R,
    LOWER_S,
    LOWER_T,
    LOWER_U,
    LOWER_V,
    LOWER_W,
    LOWER_X,
    LOWER_Y,
    LOWER_Z,
    CURLY_BRACKET_OPEN,
    VERTICAL_BAR,
    CURLY_BRACKET_CLOSE,
    TILDE,
    NON_BREAKING_SPACE = 0xA0,
    INVERTED_EXCLAMATION_MARK,
    CENT,
    POUND_SIGN,
    CURRENCY_SIGN,
    YEN_SIGN,
    BROKEN_BAR,
    SECTION_SIGN,
    DIAERESIS,
    COPYRIGHT_SYMBOL,
    FEMININE_ORDINAL_INDICATOR,
    GUILLMENTS_LEFT,
    NEGATION_SIGN,
    SOFT_HYPHEN,
    TRADEMARK_SYMBOL,
    MACRON,
    // ...
    ISO_8859_1_END = 0xFF,
} ISO_8859_1_t;
